services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #map local folder to docker container app folder
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - admin_db
  admin_db:
    image: mysql
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      #the admin that owns the mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #map debian files to: docker container
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306
